package capabilities

// catalog is the frozen first-GA REST↔MCP table. Order is the docs/07
// capability list; do not reorder or rename in place.
func catalog() []Capability {
	return []Capability{
		{
			ID: HealthLive, Title: "Health live", Version: VersionTag,
			Description: "Process liveness. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/live"}},
		},
		{
			ID: HealthReady, Title: "Health ready", Version: VersionTag,
			Description: "Proxy bound, store initialized, and management bound or explicitly off. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/ready"}},
		},
		{
			ID: VersionGet, Title: "Version", Version: VersionTag,
			Description:    "Build and protocol versions.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Version"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/version"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_version_get"}},
			ServiceMethods: []string{"Version"},
		},
		{
			ID: CapabilitiesGet, Title: "Capabilities", Version: VersionTag,
			Description:    "Capability list and protocol metadata.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "CapabilityView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/capabilities"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_capabilities_get"}, Resources: []string{"labmitm://capabilities"}},
			ServiceMethods: []string{"Capabilities"},
		},
		{
			ID: StatusGet, Title: "Agent status", Version: VersionTag,
			Description:    "Listeners, store stats, revisions, intercept on/off, and CA metadata (never the key).",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Status"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/status"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_status_get"}, Resources: []string{"labmitm://status"}},
			ServiceMethods: []string{"Status"},
		},
		{
			ID: SchemaGet, Title: "Config schema", Version: VersionTag,
			Description:    "Published v1alpha1 config JSON Schema.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/schema/config"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_schema_get"}, Resources: []string{"labmitm://schema/config"}},
			ServiceMethods: []string{"ConfigSchema"},
		},
		{
			ID: StateGet, Title: "Get state", Version: VersionTag,
			Description:    "Redacted spec plus revision metadata.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "StateView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_state_get"}, Resources: []string{"labmitm://state"}},
			ServiceMethods: []string{"GetState"},
		},
		{
			ID: StateValidate, Title: "Validate", Version: VersionTag,
			Description:    "Validate a candidate document and/or operations without writing.",
			RequiredScopes: []string{ScopeMITMAdmin}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ValidateIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:validate"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_state_validate"}},
			ServiceMethods: []string{"Validate"},
		},
		{
			ID: StateExport, Title: "Export", Version: VersionTag,
			Description:    "Canonical desired-state export plus drift material.",
			RequiredScopes: []string{ScopeMITMAdmin}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Export"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state:export"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_state_export"}},
			ServiceMethods: []string{"Export"},
		},
		{
			ID: StateReset, Title: "Reset", Version: VersionTag,
			Description:    "Reread the bootstrap mount, wipe the inbox, and swap. Never writes the file.",
			RequiredScopes: []string{ScopeMITMAdmin}, Mutating: true,
			InputSchema:    &SchemaRef{Name: "ResetIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:reset"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_state_reset"}},
			ServiceMethods: []string{"Reset"},
		},
		{
			ID: ChangesPlan, Title: "Plan", Version: VersionTag,
			Description:    "Dry-run operations against the active snapshot.",
			RequiredScopes: []string{ScopeMITMAdmin}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:plan"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_change_plan"}},
			ServiceMethods: []string{"Plan"},
		},
		{
			ID: ChangesApply, Title: "Apply", Version: VersionTag,
			Description:    "Apply operations. expectedRevision is required.",
			RequiredScopes: []string{ScopeMITMAdmin}, Mutating: true, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:apply"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_change_apply"}},
			ServiceMethods: []string{"Apply"},
		},
		{
			ID: SessionCreate, Title: "Create session", Version: VersionTag,
			Description: "Cookie + CSRF session for the flow-inspector UI. Accepts bearer.",
			Idempotent:  false, RESTOnly: true, Mutating: true,
			REST: []RESTBinding{{Method: "POST", Path: "/v1/session"}},
		},
		{
			ID: SessionDelete, Title: "Delete session", Version: VersionTag,
			Description: "Clear the flow-inspector UI session cookie.",
			Idempotent:  true, RESTOnly: true, Mutating: true,
			REST: []RESTBinding{{Method: "DELETE", Path: "/v1/session"}},
		},
		{
			ID: SessionGet, Title: "Get session", Version: VersionTag,
			Description: "Current session principal (cookie or bearer). Cookie path returns CSRF for reload recovery.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/session"}},
		},
		{
			ID: EventsStream, Title: "Events stream", Version: VersionTag,
			Description:    "REST SSE flow events. MCP uses subscriptions/listen URI-only notify.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true, DifferentBinding: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/events/stream"}},
			MCP:            &MCPBinding{Resources: []string{"labmitm://flows"}},
			ServiceMethods: []string{"Subscribe"},
		},
		{
			ID: FlowsList, Title: "List flows", Version: VersionTag,
			Description:    "Cursor-paginated flow list. HMAC cursors bind storeGeneration.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "FlowList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/flows"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flows_list"}, Resources: []string{"labmitm://flows"}},
			ServiceMethods: []string{"ListFlows"},
		},
		{
			ID: FlowsGet, Title: "Get flow", Version: VersionTag,
			Description:    "One flow including headers and truncated bodies.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Flow"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/flows/{id}"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flow_get"}, Resources: []string{"labmitm://flows/{id}"}},
			ServiceMethods: []string{"GetFlow"},
		},
		{
			ID: FlowsRequest, Title: "Raw request body", Version: VersionTag,
			Description:    "Captured request body bytes.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/flows/{id}/request"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flow_request_get"}},
			ServiceMethods: []string{"GetFlow"},
		},
		{
			ID: FlowsResponse, Title: "Raw response body", Version: VersionTag,
			Description:    "Captured response body bytes.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/flows/{id}/response"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flow_response_get"}},
			ServiceMethods: []string{"GetFlow"},
		},
		{
			ID: FlowsDelete, Title: "Delete flow", Version: VersionTag,
			Description:    "Delete one flow by id.",
			RequiredScopes: []string{ScopeMITMWrite}, Mutating: true, Idempotent: true,
			REST:           []RESTBinding{{Method: "DELETE", Path: "/v1/flows/{id}"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flow_delete"}},
			ServiceMethods: []string{"DeleteFlow"},
		},
		{
			ID: FlowsClear, Title: "Clear flows", Version: VersionTag,
			Description:    "Delete every flow. Does not bump epoch.",
			RequiredScopes: []string{ScopeMITMWrite}, Mutating: true, Idempotent: true,
			REST:           []RESTBinding{{Method: "DELETE", Path: "/v1/flows"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flows_clear"}},
			ServiceMethods: []string{"ClearFlows"},
		},
		{
			ID: FlowsWait, Title: "Wait for flow", Version: VersionTag,
			Description:    "Block until a matching flow arrives or the timeout fires.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "WaitIn"},
			OutputSchema:   &SchemaRef{Name: "Flow"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/flows:wait"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flows_wait"}},
			ServiceMethods: []string{"Wait"},
		},
		{
			ID: FlowsResume, Title: "Resume breakpoint", Version: VersionTag,
			Description:    "Resume a paused flow. Optional header/body patch.",
			RequiredScopes: []string{ScopeMITMWrite}, Mutating: true, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ResumeIn"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/flows/{id}:resume"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flow_resume"}},
			ServiceMethods: []string{"Resume"},
		},
		{
			ID: FlowsDrop, Title: "Drop breakpoint", Version: VersionTag,
			Description:    "Drop a paused flow.",
			RequiredScopes: []string{ScopeMITMWrite}, Mutating: true, Idempotent: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/flows/{id}:drop"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flow_drop"}},
			ServiceMethods: []string{"Drop"},
		},
		{
			ID: FlowsReplay, Title: "Replay flow", Version: VersionTag,
			Description:    "Replay a stored request to the origin (never hairpins the proxy). Returns a new flow id.",
			RequiredScopes: []string{ScopeMITMWrite}, Mutating: true,
			OutputSchema:   &SchemaRef{Name: "Flow"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/flows/{id}:replay"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_flow_replay"}},
			ServiceMethods: []string{"Replay"},
		},
		{
			ID: CAGet, Title: "Lab CA certificate", Version: VersionTag,
			Description:    "PEM certificate only. Never the private key.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/ca"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_ca_get"}, Resources: []string{"labmitm://ca"}},
			ServiceMethods: []string{"GetCA"},
		},
		{
			ID: AuditList, Title: "Audit list", Version: VersionTag,
			Description:    "Query recent in-memory audit events.",
			RequiredScopes: []string{ScopeMITMAuditRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "AuditQuery"},
			OutputSchema:   &SchemaRef{Name: "AuditList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_audit_query"}, Resources: []string{"labmitm://audit/recent"}},
			ServiceMethods: []string{"QueryAudit"},
		},
		{
			ID: AuditGet, Title: "Audit get", Version: VersionTag,
			Description:    "Get one audit event by ID.",
			RequiredScopes: []string{ScopeMITMAuditRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "AuditEvent"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit/{eventId}"}},
			MCP:            &MCPBinding{Tools: []string{"mitm_audit_get"}},
			ServiceMethods: []string{"GetAudit"},
		},
		{
			ID: MetricsGet, Title: "Metrics", Version: VersionTag,
			Description:    "OpenMetrics text. Served only when observability.metrics.publicPath is true.",
			RequiredScopes: []string{ScopeMITMRead}, Idempotent: true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/metrics"}},
		},
	}
}
